### ISSUE TITLE
Implement:  Android test suite

### ISSUE THREAD

**Issue by dalderliesten** [jessetilro/pixelperfect#151]
Android test suites / test cases must be implemented to raise test coverage to an acceptable level, mainly the Android Application Test is of importance.

**Comment by dmalarev** [comment]
this might not be finished by this sprint, honestly.

**Comment by dalderliesten** [comment]
No stress, shall I postpone it?

**Comment by dmalarev** [comment]
I think it will have to be postponed till next sprint, yeah.
