### ISSUE TITLE
Implement:  HUD indicators

### ISSUE THREAD

**Issue by dalderliesten** [jessetilro/pixelperfect#152]
Implement World Space Indicators that show the team score, time remaining, and the ship health.

**Comment by dalderliesten** [comment]
#164 is a first implementation of the health indicator for the demo.  The revamp for the rest of the items and the full support for VR comes later in the week.

**Comment by FlorisXll** [comment]
What we actually meant with World Space Indicator is an overview of the Route (as the name World Space Indicator infers). This gives a way for the captain to have an overview of the Route and will be given options in a two-way choice manner.

Team score, time remaining, etc. should be general HUD.

**Comment by dalderliesten** [comment]
Implemented by #189 .
