### ISSUE TITLE
Upload code to SIG.

### ISSUE THREAD

**Issue by jessetilro** [jessetilro/pixelperfect#167]
The instructions for uploading your code for SIG evaluation are available in the 'Software engineering aspects' section in Blackboard. Please make sure, well ahead of time, that the system works for you and you will be able to upload the code by the deadline. If not, please contact SIG using the contact details at the end of the document with the instructions.

**Comment by dalderliesten** [comment]
I have assigned this to @jessetilro, because the repo owner must do this, which is Jesse!
