### ISSUE TITLE
Refactor: network usage in server.

### ISSUE THREAD

**Issue by FlorisXll** [jessetilro/pixelperfect#168]
The Server usage is a mess right now. There should be one place where the server broadcasts messages (ServerListener?).

**Comment by dmalarev** [comment]
AFAIK, the ServerListener is used to interact with incoming messages, so I believe it wouldn't be the right class to refactor in.

**Comment by FlorisXll** [comment]
You are probably right. But at least the Server shouldn't be spread around all over the code.

**Comment by jessetilro** [comment]
I suggest we take a look at this after refactoring the messages and their listeners according to #226, and postpone this for now.
