### ISSUE TITLE
Implement:  Location Hints

### ISSUE THREAD

**Issue by dalderliesten** [jessetilro/pixelperfect#231]
Add the location based hints such as fires and cockpit buttons to the game, as a replacement for the captain's description display.

**Comment by FlorisXll** [comment]
To be more concrete, this involves the following things:

- Every location has its own area on the dashboard, meaning that all lights for the events of that location is grouped together.
- When an event arises a light will flicker AND a sound will be heard.
- The light bulbs have a label next to it which is visible for the captain which cannot move. Logically parameters of events will be grouped together for visual arousal.
