### ISSUE TITLE
Networking Interface - Android

### ISSUE THREAD

**Issue by dalderliesten** [jessetilro/pixelperfect#54]
Implement basic networking interface in the Android client application.

**Comment by dalderliesten** [comment]
Not a bug!

**Comment by jessetilro** [comment]
When something is done we consider it fixed right? When closing an Issue this does not necessarily mean it was resolved, so there must be some way to indicate this. Do you propose an additional label like "resolved"?

**Comment by dalderliesten** [comment]
Closing an issue means its done.  If the task is not done, it's added to the backlog and a new issue is made for the week after.
