### ISSUE TITLE
Synchronize Events Between Server and Client.

### ISSUE THREAD

**Issue by jessetilro** [jessetilro/pixelperfect#63]
When events are published in the server-side application, these must be synchronized with the client application. This way, the client application can locally verify whether the user has performed an action that resolves an active event, before submitting it to the server.

https://wiki.jmonkeyengine.org/doku.php/jme3:advanced:networking

**Comment by dmalarev** [comment]
How does the EventScheduler work?
What does it do when it publishes an event?

**Comment by jessetilro** [comment]
It sends the Event to subscribers (i.e. subscribed EventListeners). Just take a look at the code, it's not that complicated. One of the classes involved in this process should send a sort of EventMessage describing the event to all network clients.

**Comment by dmalarev** [comment]
Issue almost complete.
Only thing needed is the same thing for clients

**Comment by jessetilro** [comment]
Great, I will work on updating the client application correspondingly today.
