### ISSUE TITLE
Represent HostedConnections with Players

### ISSUE THREAD

**Issue by jessetilro** [jessetilro/pixelperfect#67]
Make the SpaceShip form a composition of Player objects. Each CrewPlayer should be connected to a HostedConnection that was made with the server.

https://wiki.jmonkeyengine.org/doku.php/jme3:advanced:networking

**Comment by dmalarev** [comment]
I added a function that saves (and updates) the HostedConnection items in an array of players.
Have yet to implement when the function is called in-game
