### ISSUE TITLE
Find a way to include jMonkeyVR dependency.

### ISSUE THREAD

**Issue by jessetilro** [jessetilro/pixelperfect#80]
Currently the jMonkeyVR library is included in the repository in its entirety. We must find a way to let the Maven tool find it by simply adding a dependency reference to the POM.

https://github.com/phr00t/jMonkeyVR

**Comment by jessetilro** [comment]
Done! I hosted it myself for the moment, maybe we find a better solution along the way. Suggestion on for example better naming are welcome.

- Repository URL: http://maven.jessetilro.nl/
- Group ID: nl.tudelft.pixelperfect
- Artifact ID: jmonkeyvr
- Version: 1.0.0

**Comment by dalderliesten** [comment]
I've written on slack that they should provide a better solution.  Thanks Jesse!
