### ISSUE TITLE
Fix EventsMessage to be Serializable.

### ISSUE THREAD

**Issue by jessetilro** [jessetilro/pixelperfect#89]
The EventsMessage must be fixed to be serializable and registered to the Serializer, otherwise it causes major networking issues.

**Comment by dmalarev** [comment]
As far as i've tested, the issue seems to be because the java.util.ArrayList class is not marked "@Serializable", so it causes the message to not be able to create

**Comment by dalderliesten** [comment]
I suggest we create a new, extendable version of the arraylist class/implementation.

**Comment by dmalarev** [comment]
A reason why the event classes cannot be serialized is because they don't have a no-argument constructor.
So we either need to rework the events so the are serializable or make it so only the captain can see that events

**Comment by FlorisXll** [comment]
Because event also have to take place on Android we must have some sort of Messages. There must be info sent in a way. The question is, will we do this with Events, Strings or ArrayLists?

**Comment by dmalarev** [comment]
I was thinking of an idea, that involves sending bits of the event (id, duration, type) as a string in the EventsMessage, so the client can know about what event it is and able to recreate it.
When the event is complete, the client sends an EventComplete message, within a string containing e.g. the event id, so the server can recognize and delete the event from the log before it expires.

**Comment by FlorisXll** [comment]
Yeah, you could make a class that is Serializable and that takes information about Events.
